package migrations

import (
	"starter/backend/models"

	"gorm.io/gorm"
)

// SeedSuppliers seeds sample supplier data
func SeedSuppliers(db *gorm.DB) error {
	suppliers := []models.Supplier{
		// Distributor Farmasi Besar
		{
			Code:            "SUP001",
			Name:            "PT. Kimia Farma Trading & Distribution",
			Address:         "Jl. Veteran No. 9, Jakarta Pusat 10110",
			Phone:           "021-3847809",
			Email:           "info@kimiafarma.co.id",
			NPWP:            "01.001.234.5-001.000",
			ContactPerson:   "Ahmad Fauzi",
			ContactPhone:    "081234567890",
			BankName:        "Bank Mandiri",
			BankAccount:     "1234567890123",
			BankAccountName: "PT Kimia Farma TBK",
			Notes:           "Distributor resmi obat-obatan dan alat kesehatan",
			IsActive:        true,
		},
		{
			Code:            "SUP002",
			Name:            "PT. Enseval Putera Megatrading Tbk",
			Address:         "Jl. Pulo Lentut No. 10, Kawasan Industri Pulogadung, Jakarta 13920",
			Phone:           "021-4603550",
			Email:           "info@enseval.com",
			NPWP:            "01.002.345.6-002.000",
			ContactPerson:   "Budi Santoso",
			ContactPhone:    "082345678901",
			BankName:        "Bank BCA",
			BankAccount:     "2345678901234",
			BankAccountName: "PT Enseval Putera Megatrading",
			Notes:           "Distributor obat-obatan nasional",
			IsActive:        true,
		},
		{
			Code:            "SUP003",
			Name:            "PT. Anugrah Argon Medica",
			Address:         "Jl. Raya Jakarta Bogor KM 38, Depok 16953",
			Phone:           "021-8752345",
			Email:           "aam@argon.co.id",
			NPWP:            "01.003.456.7-003.000",
			ContactPerson:   "Dewi Lestari",
			ContactPhone:    "083456789012",
			BankName:        "Bank BNI",
			BankAccount:     "3456789012345",
			BankAccountName: "PT Anugrah Argon Medica",
			Notes:           "Distributor alat kesehatan dan farmasi",
			IsActive:        true,
		},
		{
			Code:            "SUP004",
			Name:            "PT. Dos Ni Roha",
			Address:         "Jl. Letjen Suprapto No. 35, Cempaka Putih, Jakarta 10520",
			Phone:           "021-4240088",
			Email:           "info@dosni.co.id",
			NPWP:            "01.004.567.8-004.000",
			ContactPerson:   "Eko Prasetyo",
			ContactPhone:    "084567890123",
			BankName:        "Bank BRI",
			BankAccount:     "4567890123456",
			BankAccountName: "PT Dos Ni Roha",
			Notes:           "Distributor obat generik berlogo",
			IsActive:        true,
		},
		{
			Code:            "SUP005",
			Name:            "PT. Mensa Bina Sukses",
			Address:         "Jl. Industri Raya No. 8, Tangerang 15135",
			Phone:           "021-5523456",
			Email:           "mensa@bina.co.id",
			NPWP:            "01.005.678.9-005.000",
			ContactPerson:   "Fitri Handayani",
			ContactPhone:    "085678901234",
			BankName:        "Bank Mandiri",
			BankAccount:     "5678901234567",
			BankAccountName: "PT Mensa Bina Sukses",
			Notes:           "Supplier alat medis dan laboratorium",
			IsActive:        true,
		},
		// Supplier Alat Kesehatan
		{
			Code:            "SUP006",
			Name:            "PT. Indofarma Global Medika",
			Address:         "Jl. Cibitung-Bekasi Km 28, Bekasi 17530",
			Phone:           "021-88326660",
			Email:           "igm@indofarma.co.id",
			NPWP:            "01.006.789.0-006.000",
			ContactPerson:   "Galih Permana",
			ContactPhone:    "086789012345",
			BankName:        "Bank BTN",
			BankAccount:     "6789012345678",
			BankAccountName: "PT Indofarma Global Medika",
			Notes:           "Anak perusahaan Indofarma untuk distribusi",
			IsActive:        true,
		},
		{
			Code:            "SUP007",
			Name:            "PT. Parit Padang Global",
			Address:         "Jl. Bendungan Jatiluhur No. 56, Jakarta Pusat 10210",
			Phone:           "021-5704567",
			Email:           "ppg@paritpadang.com",
			NPWP:            "01.007.890.1-007.000",
			ContactPerson:   "Hendra Wijaya",
			ContactPhone:    "087890123456",
			BankName:        "Bank BCA",
			BankAccount:     "7890123456789",
			BankAccountName: "PT Parit Padang Global",
			Notes:           "Supplier alat diagnostik dan reagensia",
			IsActive:        true,
		},
		{
			Code:            "SUP008",
			Name:            "PT. Merck Indonesia Tbk",
			Address:         "Jl. TB Simatupang No. 8, Jakarta Selatan 12430",
			Phone:           "021-78423456",
			Email:           "info@merck.co.id",
			NPWP:            "01.008.901.2-008.000",
			ContactPerson:   "Indah Sari",
			ContactPhone:    "088901234567",
			BankName:        "Bank CIMB Niaga",
			BankAccount:     "8901234567890",
			BankAccountName: "PT Merck Indonesia Tbk",
			Notes:           "Produsen dan distributor obat paten",
			IsActive:        true,
		},
	}

	for _, supplier := range suppliers {
		var existing models.Supplier
		if err := db.Where("code = ?", supplier.Code).First(&existing).Error; err == gorm.ErrRecordNotFound {
			if err := db.Create(&supplier).Error; err != nil {
				return err
			}
		}
	}

	return nil
}

// SeedInventories seeds sample inventory data
func SeedInventories(db *gorm.DB) error {
	inventories := []models.Inventory{
		// Alat Medis
		{
			Code:           "INV001",
			Name:           "Stetoskop Littmann Classic III",
			Description:    "Stetoskop akustik berkualitas tinggi untuk pemeriksaan jantung dan paru-paru",
			Category:       models.InventoryCategoryMedical,
			Unit:           "unit",
			Brand:          "3M Littmann",
			Model:          "Classic III",
			MinStock:       5,
			MaxStock:       20,
			Price:          1500000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Acoustic, dual-sided chestpiece, 27 inch tubing",
		},
		{
			Code:           "INV002",
			Name:           "Tensimeter Digital Omron",
			Description:    "Alat ukur tekanan darah digital otomatis",
			Category:       models.InventoryCategoryMedical,
			Unit:           "unit",
			Brand:          "Omron",
			Model:          "HEM-7130",
			MinStock:       10,
			MaxStock:       30,
			Price:          450000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Digital display, memory 60 readings, irregular heartbeat detection",
		},
		{
			Code:           "INV003",
			Name:           "Thermometer Infrared",
			Description:    "Thermometer non-contact untuk pengukuran suhu tubuh",
			Category:       models.InventoryCategoryMedical,
			Unit:           "unit",
			Brand:          "Beurer",
			Model:          "FT-90",
			MinStock:       20,
			MaxStock:       50,
			Price:          350000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Non-contact, 1 second measurement, fever alarm",
		},
		{
			Code:           "INV004",
			Name:           "Pulse Oximeter",
			Description:    "Alat ukur saturasi oksigen dan denyut nadi",
			Category:       models.InventoryCategoryMedical,
			Unit:           "unit",
			Brand:          "Elitech",
			Model:          "FOX-2",
			MinStock:       15,
			MaxStock:       40,
			Price:          250000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "SpO2 range 70-99%, pulse rate 30-250 bpm, OLED display",
		},
		{
			Code:           "INV005",
			Name:           "Nebulizer Compressor",
			Description:    "Alat terapi inhalasi untuk saluran pernapasan",
			Category:       models.InventoryCategoryMedical,
			Unit:           "unit",
			Brand:          "Omron",
			Model:          "NE-C28",
			MinStock:       5,
			MaxStock:       15,
			Price:          650000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Compressor type, particle size 3μm, noise level <60dB",
		},
		// Bahan Habis Pakai
		{
			Code:          "INV006",
			Name:          "Sarung Tangan Latex Examination",
			Description:   "Sarung tangan latex sekali pakai untuk pemeriksaan",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "box",
			Brand:         "Sensi",
			Model:         "Standard",
			MinStock:      50,
			MaxStock:      200,
			Price:         85000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 100 pcs per box, ukuran S/M/L tersedia",
		},
		{
			Code:          "INV007",
			Name:          "Masker Bedah 3 Ply",
			Description:   "Masker medis 3 lapis sekali pakai",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "box",
			Brand:         "Sensi",
			Model:         "Earloop",
			MinStock:      100,
			MaxStock:      500,
			Price:         45000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 50 pcs per box",
		},
		{
			Code:          "INV008",
			Name:          "Spuit Disposable 3ml",
			Description:   "Syringe sekali pakai dengan jarum 23G",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "box",
			Brand:         "Terumo",
			Model:         "SS-03L2338",
			MinStock:      100,
			MaxStock:      500,
			Price:         120000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 100 pcs per box, jarum 23G x 1 inch",
		},
		{
			Code:          "INV009",
			Name:          "Spuit Disposable 5ml",
			Description:   "Syringe sekali pakai dengan jarum 21G",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "box",
			Brand:         "Terumo",
			Model:         "SS-05L2138",
			MinStock:      100,
			MaxStock:      500,
			Price:         135000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 100 pcs per box, jarum 21G x 1.5 inch",
		},
		{
			Code:          "INV010",
			Name:          "Infus Set Dewasa",
			Description:   "Set infus untuk pasien dewasa",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "pcs",
			Brand:         "Terumo",
			Model:         "TS-A20L",
			MinStock:      200,
			MaxStock:      1000,
			Price:         12000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "20 drops/ml, panjang selang 150cm",
		},
		{
			Code:          "INV011",
			Name:          "IV Catheter 18G",
			Description:   "Kateter intravena untuk akses vena",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "box",
			Brand:         "Terumo",
			Model:         "Surflo IV",
			MinStock:      50,
			MaxStock:      200,
			Price:         250000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 50 pcs per box",
		},
		{
			Code:          "INV012",
			Name:          "Kapas Bulat Steril",
			Description:   "Kapas bulat steril untuk pembersihan luka",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "pack",
			Brand:         "Husada",
			Model:         "Standard",
			MinStock:      100,
			MaxStock:      500,
			Price:         15000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 100 pcs per pack",
		},
		{
			Code:          "INV013",
			Name:          "Kasa Steril 10x10cm",
			Description:   "Kasa steril untuk pembalut luka",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "pack",
			Brand:         "Husada",
			Model:         "16 ply",
			MinStock:      100,
			MaxStock:      500,
			Price:         25000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 10 lembar per pack",
		},
		{
			Code:          "INV014",
			Name:          "Plester Luka Waterproof",
			Description:   "Plester anti air untuk luka kecil",
			Category:      models.InventoryCategoryConsumable,
			Unit:          "box",
			Brand:         "Hansaplast",
			Model:         "Aqua Protect",
			MinStock:      50,
			MaxStock:      200,
			Price:         35000,
			IsConsumable:  true,
			IsReusable:    false,
			RequireSerial: false,
			IsActive:      true,
			Notes:         "Isi 20 pcs per box",
		},
		// Peralatan
		{
			Code:           "INV015",
			Name:           "Kursi Roda Standard",
			Description:    "Kursi roda lipat untuk mobilitas pasien",
			Category:       models.InventoryCategoryEquipment,
			Unit:           "unit",
			Brand:          "GEA Medical",
			Model:          "FS-809",
			MinStock:       5,
			MaxStock:       20,
			Price:          1200000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Chrome steel frame, detachable footrest, weight capacity 100kg",
		},
		{
			Code:           "INV016",
			Name:           "Tiang Infus Stainless",
			Description:    "Tiang infus berdiri dengan roda",
			Category:       models.InventoryCategoryEquipment,
			Unit:           "unit",
			Brand:          "GEA Medical",
			Model:          "YD-01",
			MinStock:       20,
			MaxStock:       50,
			Price:          350000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  false,
			IsActive:       true,
			Specifications: "Height adjustable, 4 hooks, 5 wheels",
		},
		{
			Code:           "INV017",
			Name:           "Brankar Pasien Lipat",
			Description:    "Brankar lipat untuk pemindahan pasien",
			Category:       models.InventoryCategoryEquipment,
			Unit:           "unit",
			Brand:          "GEA Medical",
			Model:          "YQC-2L",
			MinStock:       3,
			MaxStock:       10,
			Price:          2500000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Foldable, aluminium frame, load capacity 159kg",
		},
		// Elektronik
		{
			Code:           "INV018",
			Name:           "ECG 12 Lead",
			Description:    "Elektrokardiograf 12 lead untuk pemeriksaan jantung",
			Category:       models.InventoryCategoryElectronic,
			Unit:           "unit",
			Brand:          "Fukuda Denshi",
			Model:          "FX-7202",
			MinStock:       2,
			MaxStock:       5,
			Price:          35000000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "12 lead simultaneous acquisition, thermal printer, LCD display",
		},
		{
			Code:           "INV019",
			Name:           "Patient Monitor 5 Parameter",
			Description:    "Monitor pasien dengan 5 parameter vital sign",
			Category:       models.InventoryCategoryElectronic,
			Unit:           "unit",
			Brand:          "Mindray",
			Model:          "iPM-9800",
			MinStock:       3,
			MaxStock:       10,
			Price:          45000000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "ECG, SpO2, NIBP, Resp, Temp, 12.1 inch touchscreen",
		},
		{
			Code:           "INV020",
			Name:           "Suction Pump Portable",
			Description:    "Pompa suction portable untuk penghisapan lendir",
			Category:       models.InventoryCategoryElectronic,
			Unit:           "unit",
			Brand:          "Yuwell",
			Model:          "7E-A",
			MinStock:       5,
			MaxStock:       15,
			Price:          1800000,
			IsConsumable:   false,
			IsReusable:     true,
			RequireSerial:  true,
			IsActive:       true,
			Specifications: "Max vacuum >80kPa, flow rate >20L/min, 1L bottle",
		},
	}

	for _, inventory := range inventories {
		var existing models.Inventory
		if err := db.Where("code = ?", inventory.Code).First(&existing).Error; err == gorm.ErrRecordNotFound {
			if err := db.Create(&inventory).Error; err != nil {
				return err
			}
		}
	}

	return nil
}

// SeedMedicines seeds sample medicine data
func SeedMedicines(db *gorm.DB) error {
	medicines := []models.Medicine{
		// Obat Generik - Analgesik & Antipiretik
		{
			Code:             "MED001",
			Name:             "Paracetamol 500mg",
			GenericName:      "Paracetamol",
			Description:      "Tablet analgesik dan antipiretik",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormTablet,
			Strength:         "500mg",
			Unit:             "tablet",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    150,
			SellingPrice:     500,
			Indication:       "Meredakan nyeri ringan hingga sedang, menurunkan demam",
			Contraindication: "Hipersensitif terhadap paracetamol, gangguan fungsi hati berat",
			SideEffects:      "Reaksi alergi, gangguan fungsi hati pada penggunaan jangka panjang",
			Dosage:           "Dewasa: 500-1000mg setiap 4-6 jam, maksimal 4g per hari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    false,
		},
		{
			Code:             "MED002",
			Name:             "Ibuprofen 400mg",
			GenericName:      "Ibuprofen",
			Description:      "Tablet anti-inflamasi non-steroid",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeLimited,
			Form:             models.MedicineFormTablet,
			Strength:         "400mg",
			Unit:             "tablet",
			Manufacturer:     "PT Indofarma",
			MinStock:         300,
			MaxStock:         1500,
			PurchasePrice:    200,
			SellingPrice:     800,
			Indication:       "Nyeri, demam, peradangan, arthritis",
			Contraindication: "Ulkus peptikum aktif, gangguan ginjal berat, kehamilan trimester 3",
			SideEffects:      "Gangguan GI, pusing, ruam kulit",
			Dosage:           "Dewasa: 200-400mg 3-4x sehari setelah makan",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    false,
		},
		// Antibiotik
		{
			Code:             "MED003",
			Name:             "Amoxicillin 500mg",
			GenericName:      "Amoxicillin",
			Description:      "Kapsul antibiotik golongan penisilin",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormCapsule,
			Strength:         "500mg",
			Unit:             "kapsul",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         300,
			MaxStock:         1500,
			PurchasePrice:    350,
			SellingPrice:     1200,
			Indication:       "Infeksi saluran pernapasan, saluran kemih, kulit dan jaringan lunak",
			Contraindication: "Hipersensitif terhadap penisilin, riwayat reaksi alergi berat",
			SideEffects:      "Diare, mual, ruam kulit, reaksi alergi",
			Dosage:           "Dewasa: 500mg 3x sehari selama 7-10 hari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 25°C",
			IsActive:         true,
			RequireRecipe:    true,
		},
		{
			Code:             "MED004",
			Name:             "Ciprofloxacin 500mg",
			GenericName:      "Ciprofloxacin",
			Description:      "Tablet antibiotik golongan fluorokuinolon",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormTablet,
			Strength:         "500mg",
			Unit:             "tablet",
			Manufacturer:     "PT Dexa Medica",
			MinStock:         200,
			MaxStock:         1000,
			PurchasePrice:    450,
			SellingPrice:     1500,
			Indication:       "Infeksi saluran kemih, saluran pernapasan, gastrointestinal",
			Contraindication: "Hipersensitif terhadap kuinolon, kehamilan, menyusui, anak di bawah 18 tahun",
			SideEffects:      "Mual, diare, pusing, fotosensitivitas, tendinitis",
			Dosage:           "Dewasa: 250-750mg 2x sehari",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C",
			IsActive:         true,
			RequireRecipe:    true,
		},
		{
			Code:             "MED005",
			Name:             "Ceftriaxone Injection 1g",
			GenericName:      "Ceftriaxone",
			Description:      "Injeksi antibiotik sefalosporin generasi ketiga",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormInjection,
			Strength:         "1g",
			Unit:             "vial",
			Manufacturer:     "PT Sanbe Farma",
			MinStock:         100,
			MaxStock:         500,
			PurchasePrice:    15000,
			SellingPrice:     35000,
			Indication:       "Infeksi berat, sepsis, meningitis, pneumonia",
			Contraindication: "Hipersensitif terhadap sefalosporin, neonatus dengan hiperbilirubinemia",
			SideEffects:      "Reaksi alergi, diare, nyeri di tempat injeksi",
			Dosage:           "Dewasa: 1-2g IV/IM sekali sehari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 25°C, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    true,
		},
		// Antihipertensi
		{
			Code:             "MED006",
			Name:             "Amlodipine 5mg",
			GenericName:      "Amlodipine",
			Description:      "Tablet antihipertensi golongan CCB",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormTablet,
			Strength:         "5mg",
			Unit:             "tablet",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    180,
			SellingPrice:     700,
			Indication:       "Hipertensi, angina pektoris",
			Contraindication: "Hipersensitif, hipotensi berat, syok kardiogenik",
			SideEffects:      "Edema perifer, pusing, palpitasi, flushing",
			Dosage:           "Dewasa: 5-10mg sekali sehari",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C",
			IsActive:         true,
			RequireRecipe:    true,
		},
		{
			Code:             "MED007",
			Name:             "Captopril 25mg",
			GenericName:      "Captopril",
			Description:      "Tablet antihipertensi golongan ACE inhibitor",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormTablet,
			Strength:         "25mg",
			Unit:             "tablet",
			Manufacturer:     "PT Indofarma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    120,
			SellingPrice:     500,
			Indication:       "Hipertensi, gagal jantung, pasca infark miokard",
			Contraindication: "Hipersensitif, angioedema, kehamilan, stenosis arteri renalis bilateral",
			SideEffects:      "Batuk kering, hipotensi, hiperkalemia, gangguan rasa",
			Dosage:           "Dewasa: 12.5-50mg 2-3x sehari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    true,
		},
		// Antidiabetes
		{
			Code:             "MED008",
			Name:             "Metformin 500mg",
			GenericName:      "Metformin HCl",
			Description:      "Tablet antidiabetes oral golongan biguanid",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormTablet,
			Strength:         "500mg",
			Unit:             "tablet",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         500,
			MaxStock:         2500,
			PurchasePrice:    150,
			SellingPrice:     600,
			Indication:       "Diabetes mellitus tipe 2",
			Contraindication: "Gangguan ginjal berat, asidosis metabolik, gagal jantung akut",
			SideEffects:      "Gangguan GI, asidosis laktat (jarang), defisiensi vitamin B12",
			Dosage:           "Dewasa: 500-850mg 2-3x sehari bersama makanan",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C",
			IsActive:         true,
			RequireRecipe:    true,
		},
		{
			Code:             "MED009",
			Name:             "Glimepiride 2mg",
			GenericName:      "Glimepiride",
			Description:      "Tablet antidiabetes oral golongan sulfonilurea",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormTablet,
			Strength:         "2mg",
			Unit:             "tablet",
			Manufacturer:     "PT Dexa Medica",
			MinStock:         300,
			MaxStock:         1500,
			PurchasePrice:    350,
			SellingPrice:     1200,
			Indication:       "Diabetes mellitus tipe 2",
			Contraindication: "DM tipe 1, ketoasidosis diabetik, gangguan hati/ginjal berat",
			SideEffects:      "Hipoglikemia, gangguan GI, reaksi alergi",
			Dosage:           "Dewasa: 1-4mg sekali sehari sebelum makan pagi",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    true,
		},
		// Obat Saluran Cerna
		{
			Code:             "MED010",
			Name:             "Omeprazole 20mg",
			GenericName:      "Omeprazole",
			Description:      "Kapsul proton pump inhibitor",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeLimited,
			Form:             models.MedicineFormCapsule,
			Strength:         "20mg",
			Unit:             "kapsul",
			Manufacturer:     "PT Kalbe Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    250,
			SellingPrice:     900,
			Indication:       "GERD, ulkus peptikum, sindrom Zollinger-Ellison",
			Contraindication: "Hipersensitif terhadap PPI",
			SideEffects:      "Sakit kepala, diare, mual, nyeri perut",
			Dosage:           "Dewasa: 20-40mg sekali sehari sebelum makan pagi",
			StorageInfo:      "Simpan di tempat kering, suhu 15-25°C",
			IsActive:         true,
			RequireRecipe:    false,
		},
		{
			Code:             "MED011",
			Name:             "Ranitidine 150mg",
			GenericName:      "Ranitidine HCl",
			Description:      "Tablet H2 blocker untuk gangguan lambung",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeLimited,
			Form:             models.MedicineFormTablet,
			Strength:         "150mg",
			Unit:             "tablet",
			Manufacturer:     "PT Indofarma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    180,
			SellingPrice:     700,
			Indication:       "Ulkus peptikum, GERD, sindrom Zollinger-Ellison",
			Contraindication: "Hipersensitif terhadap ranitidine, porfiria akut",
			SideEffects:      "Sakit kepala, pusing, konstipasi",
			Dosage:           "Dewasa: 150mg 2x sehari atau 300mg sebelum tidur",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    false,
		},
		// Obat Batuk & Pilek
		{
			Code:             "MED012",
			Name:             "Ambroxol 30mg",
			GenericName:      "Ambroxol HCl",
			Description:      "Tablet mukolitik untuk batuk berdahak",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormTablet,
			Strength:         "30mg",
			Unit:             "tablet",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    100,
			SellingPrice:     400,
			Indication:       "Batuk berdahak, gangguan saluran pernapasan",
			Contraindication: "Hipersensitif, kehamilan trimester pertama",
			SideEffects:      "Gangguan GI ringan, reaksi alergi kulit",
			Dosage:           "Dewasa: 30mg 3x sehari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    false,
		},
		{
			Code:             "MED013",
			Name:             "Cetirizine 10mg",
			GenericName:      "Cetirizine HCl",
			Description:      "Tablet antihistamin untuk alergi",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormTablet,
			Strength:         "10mg",
			Unit:             "tablet",
			Manufacturer:     "PT Sanbe Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    150,
			SellingPrice:     600,
			Indication:       "Rhinitis alergi, urtikaria, reaksi alergi",
			Contraindication: "Hipersensitif, gangguan ginjal berat",
			SideEffects:      "Mengantuk, mulut kering, sakit kepala",
			Dosage:           "Dewasa: 10mg sekali sehari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    false,
		},
		// Sirup
		{
			Code:             "MED014",
			Name:             "Paracetamol Sirup 120mg/5ml",
			GenericName:      "Paracetamol",
			Description:      "Sirup analgesik dan antipiretik untuk anak",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormSyrup,
			Strength:         "120mg/5ml",
			Unit:             "botol",
			Manufacturer:     "PT Sanbe Farma",
			MinStock:         200,
			MaxStock:         800,
			PurchasePrice:    8000,
			SellingPrice:     15000,
			Indication:       "Demam dan nyeri ringan pada anak",
			Contraindication: "Hipersensitif terhadap paracetamol, gangguan hati berat",
			SideEffects:      "Reaksi alergi, gangguan fungsi hati pada overdosis",
			Dosage:           "Anak: 10-15mg/kgBB setiap 4-6 jam",
			StorageInfo:      "Simpan di tempat sejuk, suhu di bawah 25°C",
			IsActive:         true,
			RequireRecipe:    false,
			Notes:            "Botol 60ml",
		},
		{
			Code:             "MED015",
			Name:             "Amoxicillin Sirup 125mg/5ml",
			GenericName:      "Amoxicillin",
			Description:      "Sirup antibiotik untuk anak",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormSyrup,
			Strength:         "125mg/5ml",
			Unit:             "botol",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         150,
			MaxStock:         600,
			PurchasePrice:    12000,
			SellingPrice:     25000,
			Indication:       "Infeksi bakteri pada anak",
			Contraindication: "Hipersensitif terhadap penisilin",
			SideEffects:      "Diare, mual, ruam kulit",
			Dosage:           "Anak: 25-50mg/kgBB/hari terbagi 3 dosis",
			StorageInfo:      "Setelah dilarutkan simpan di lemari es, gunakan dalam 7 hari",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Botol 60ml, perlu dilarutkan dengan air matang",
		},
		// Obat Tetes
		{
			Code:             "MED016",
			Name:             "Chloramphenicol Tetes Mata 0.5%",
			GenericName:      "Chloramphenicol",
			Description:      "Tetes mata antibiotik",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormDrops,
			Strength:         "0.5%",
			Unit:             "botol",
			Manufacturer:     "PT Cendo",
			MinStock:         100,
			MaxStock:         400,
			PurchasePrice:    8000,
			SellingPrice:     18000,
			Indication:       "Infeksi mata bakteri, konjungtivitis",
			Contraindication: "Hipersensitif, gangguan sumsum tulang",
			SideEffects:      "Iritasi mata, penglihatan kabur sementara",
			Dosage:           "Teteskan 1-2 tetes pada mata yang terinfeksi 3-4x sehari",
			StorageInfo:      "Simpan di tempat sejuk, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Botol 10ml",
		},
		// Injeksi
		{
			Code:             "MED017",
			Name:             "Ketorolac Injection 30mg/ml",
			GenericName:      "Ketorolac Tromethamine",
			Description:      "Injeksi NSAID untuk nyeri akut",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormInjection,
			Strength:         "30mg/ml",
			Unit:             "ampul",
			Manufacturer:     "PT Dexa Medica",
			MinStock:         100,
			MaxStock:         500,
			PurchasePrice:    8500,
			SellingPrice:     20000,
			Indication:       "Nyeri akut sedang hingga berat pasca operasi",
			Contraindication: "Ulkus GI aktif, gangguan ginjal berat, kehamilan, menyusui",
			SideEffects:      "Nyeri di tempat injeksi, gangguan GI, pusing",
			Dosage:           "Dewasa: 30mg IV/IM setiap 6 jam, maksimal 5 hari",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Ampul 1ml",
		},
		{
			Code:             "MED018",
			Name:             "Ondansetron Injection 4mg/2ml",
			GenericName:      "Ondansetron HCl",
			Description:      "Injeksi antiemetik",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormInjection,
			Strength:         "4mg/2ml",
			Unit:             "ampul",
			Manufacturer:     "PT Sanbe Farma",
			MinStock:         100,
			MaxStock:         500,
			PurchasePrice:    12000,
			SellingPrice:     28000,
			Indication:       "Mual dan muntah pasca operasi atau kemoterapi",
			Contraindication: "Hipersensitif, penggunaan bersamaan dengan apomorphine",
			SideEffects:      "Sakit kepala, konstipasi, flushing",
			Dosage:           "Dewasa: 4-8mg IV lambat sebelum anestesi atau kemoterapi",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Ampul 2ml",
		},
		// Infus
		{
			Code:             "MED019",
			Name:             "Ringer Laktat Infusion 500ml",
			GenericName:      "Ringer Lactate",
			Description:      "Larutan infus elektrolit isotonik",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormInfusion,
			Strength:         "500ml",
			Unit:             "botol",
			Manufacturer:     "PT Otsuka Indonesia",
			MinStock:         200,
			MaxStock:         1000,
			PurchasePrice:    12000,
			SellingPrice:     25000,
			Indication:       "Dehidrasi, syok, pengganti cairan tubuh",
			Contraindication: "Edema paru, gagal jantung kongestif, hipernatremia",
			SideEffects:      "Kelebihan cairan jika diberikan berlebihan",
			Dosage:           "Sesuai kebutuhan cairan pasien, biasanya 20-30 tetes/menit",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Botol kaca 500ml",
		},
		{
			Code:             "MED020",
			Name:             "NaCl 0.9% Infusion 500ml",
			GenericName:      "Sodium Chloride 0.9%",
			Description:      "Larutan infus normal saline",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormInfusion,
			Strength:         "0.9%",
			Unit:             "botol",
			Manufacturer:     "PT Widatra Bhakti",
			MinStock:         200,
			MaxStock:         1000,
			PurchasePrice:    10000,
			SellingPrice:     22000,
			Indication:       "Dehidrasi, pengencer obat injeksi, pembilasan luka",
			Contraindication: "Hipernatremia, retensi cairan",
			SideEffects:      "Kelebihan cairan dan natrium jika berlebihan",
			Dosage:           "Sesuai kebutuhan, biasanya 500-1000ml per hari",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Botol plastik 500ml",
		},
		// Salep/Krim
		{
			Code:             "MED021",
			Name:             "Gentamicin Cream 0.1%",
			GenericName:      "Gentamicin Sulfate",
			Description:      "Krim antibiotik topikal",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeHard,
			Form:             models.MedicineFormCream,
			Strength:         "0.1%",
			Unit:             "tube",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         100,
			MaxStock:         400,
			PurchasePrice:    8000,
			SellingPrice:     18000,
			Indication:       "Infeksi kulit bakteri, luka terinfeksi",
			Contraindication: "Hipersensitif terhadap aminoglikosida",
			SideEffects:      "Iritasi kulit, dermatitis kontak",
			Dosage:           "Oleskan tipis 3-4x sehari pada area terinfeksi",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 25°C",
			IsActive:         true,
			RequireRecipe:    true,
			Notes:            "Tube 5g",
		},
		{
			Code:             "MED022",
			Name:             "Hydrocortisone Ointment 2.5%",
			GenericName:      "Hydrocortisone",
			Description:      "Salep kortikosteroid topikal",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeLimited,
			Form:             models.MedicineFormOintment,
			Strength:         "2.5%",
			Unit:             "tube",
			Manufacturer:     "PT Konimex",
			MinStock:         100,
			MaxStock:         400,
			PurchasePrice:    12000,
			SellingPrice:     25000,
			Indication:       "Dermatitis, eksim, reaksi alergi kulit",
			Contraindication: "Infeksi kulit viral/fungal, rosasea, akne",
			SideEffects:      "Penipisan kulit pada penggunaan lama, infeksi sekunder",
			Dosage:           "Oleskan tipis 2-3x sehari pada area yang terkena",
			StorageInfo:      "Simpan di tempat kering, suhu 15-30°C",
			IsActive:         true,
			RequireRecipe:    false,
			Notes:            "Tube 5g",
		},
		// Vitamin & Suplemen
		{
			Code:             "MED023",
			Name:             "Vitamin C 500mg",
			GenericName:      "Ascorbic Acid",
			Description:      "Tablet vitamin C untuk daya tahan tubuh",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormTablet,
			Strength:         "500mg",
			Unit:             "tablet",
			Manufacturer:     "PT Indofarma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    100,
			SellingPrice:     400,
			Indication:       "Defisiensi vitamin C, meningkatkan daya tahan tubuh",
			Contraindication: "Hipersensitif, batu ginjal oksalat",
			SideEffects:      "Gangguan GI pada dosis tinggi",
			Dosage:           "Dewasa: 500-1000mg sekali sehari",
			StorageInfo:      "Simpan di tempat kering, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    false,
		},
		{
			Code:             "MED024",
			Name:             "Vitamin B Complex",
			GenericName:      "Vitamin B1, B2, B6, B12, Nicotinamide",
			Description:      "Tablet multivitamin B kompleks",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormTablet,
			Strength:         "Standard",
			Unit:             "tablet",
			Manufacturer:     "PT Kimia Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    80,
			SellingPrice:     350,
			Indication:       "Defisiensi vitamin B, neuritis, kelelahan",
			Contraindication: "Hipersensitif terhadap komponen",
			SideEffects:      "Jarang, mual ringan",
			Dosage:           "Dewasa: 1 tablet 1-3x sehari",
			StorageInfo:      "Simpan di tempat kering, terlindung dari cahaya",
			IsActive:         true,
			RequireRecipe:    false,
		},
		{
			Code:             "MED025",
			Name:             "Calcium Lactate 500mg",
			GenericName:      "Calcium Lactate",
			Description:      "Tablet suplemen kalsium",
			Category:         models.MedicineCategoryGeneric,
			Type:             models.MedicineTypeOTC,
			Form:             models.MedicineFormTablet,
			Strength:         "500mg",
			Unit:             "tablet",
			Manufacturer:     "PT Sanbe Farma",
			MinStock:         500,
			MaxStock:         2000,
			PurchasePrice:    120,
			SellingPrice:     500,
			Indication:       "Defisiensi kalsium, osteoporosis, kehamilan",
			Contraindication: "Hiperkalsemia, batu ginjal kalsium",
			SideEffects:      "Konstipasi, gangguan GI",
			Dosage:           "Dewasa: 500-1000mg 2-3x sehari",
			StorageInfo:      "Simpan di tempat kering, suhu di bawah 30°C",
			IsActive:         true,
			RequireRecipe:    false,
		},
	}

	for _, medicine := range medicines {
		var existing models.Medicine
		if err := db.Where("code = ?", medicine.Code).First(&existing).Error; err == gorm.ErrRecordNotFound {
			if err := db.Create(&medicine).Error; err != nil {
				return err
			}
		}
	}

	return nil
}

// SeedInventoryMedicineSupplier runs all seeding functions for inventory, medicine, and supplier
func SeedInventoryMedicineSupplier(db *gorm.DB) error {
	if err := SeedSuppliers(db); err != nil {
		return err
	}
	if err := SeedInventories(db); err != nil {
		return err
	}
	if err := SeedMedicines(db); err != nil {
		return err
	}
	return nil
}
